apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    name: imagemagick-fuzzing-pod

spec:

    replicas:

    template:

        metadata:

            labels:

                target: ImageMagick

        spec:

            containers:

            - name: imagemagick-fuzzer
              image: ouspg/libfuzzer-imagemagick:ops-testing
