version: '2'

## Build: docker-compose build <service>
## Run: docker-compose run <service>

## Note: Change volumes and command to match your system.

services:

## libfuzzer base image

  libfuzzer-base:
      build: ./base/libfuzzer-base
      image: ouspg/libfuzzer-base

## ImageMagick stub, with automatic crash-repro minimizer

  ImageMagick:
      build: ./stubs/ImageMagick
      image: ouspg/libfuzzer-imagemagick
      volumes:
        - ~/results/:/results
        - ~/samples/:/samples
      mem_limit: 4g
      shm_size: 512M
      environment:
        MINIMIZE: "true"
      entrypoint: '/src/scripts/fuzz.sh'
      command: [
        '/src/ImageMagick/ImageMagick_fuzzer',
        '-rss_limit_mb=4096',
        '-detect_leaks=0',
        '-exact_artifact_path=/dev/shm/repro-file',
        '-max_len=1000',
        '-use_counters=1',
        '-max_total_time=3600',
        '/samples/libfuzzer-imagemagick'
      ]

## libxml2 stub

  libxml2:
      build: ./stubs/libxml2
      image: ouspg/libfuzzer-libxml2
      shm_size: 512M
      mem_limit: 4g
      volumes:
          - ~/results/:/results
          - ~/samples/:/samples
      environment:
          LD_LIBRARY_PATH: "/src/libxml2/.libs/"
      command: [
        '/src/libxml2/libxml2_fuzzer',
        '-rss_limit_mb=4096',
        '-detect_leaks=0',
        '-exact_artifact_path=/dev/shm/repro-file',
        '-max_len=5000',
        '-use_counters=1',
        '-max_total_time=600',
        '/samples/libfuzzer-libxml'
      ]

## libxslt

  libxslt:
      build: ./stubs/libxslt
      image: ouspg/libfuzzer-libxslt
      shm_size: 512M
      mem_limit: 4g
      volumes:
          - ~/results/:/results
          - ~/samples/:/samples
      environment:
          LD_LIBRARY_PATH: "/src/libxslt/libxslt/.libs/"
      command: [
        '/src/libxslt/libxslt_fuzzer',
        '-rss_limit_mb=4096',
        '-detect_leaks=0',
        '-exact_artifact_path=/dev/shm/repro-file',
        '-max_len=5000',
        '-use_counters=1',
        '-max_total_time=600',
        '/samples/libfuzzer-libxslt'
      ]

## libav stub

  libav:
      build: ./stubs/libav
      image: ouspg/libfuzzer-libav
      volumes:
        - ~/results/:/results
        - ~/samples/:/samples
      mem_limit: 4g
      shm_size: 512M
      entrypoint: '/src/scripts/fuzz.sh'
      command: [
        '/src/libav/libav_fuzzer',
        '-rss_limit_mb=4096',
        '-detect_leaks=0',
        '-exact_artifact_path=/dev/shm/repro-file',
        '-max_len=1000',
        '-timeout=5',
        '-use_counters=1',
        '-max_total_time=3600',
        '/samples/libfuzzer-libav'
      ]

## Haskell base image

  libfuzzer-base-haskell:
      build: ./base/libfuzzer-base-haskell
      image: ouspg/libfuzzer-base-haskell

## Haskell stub

  haskell-x509:
      build: ./stubs/haskell-x509
      image: ouspg/libfuzzer-haskell-x509
