apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    name: libav-pod

spec:

    replicas:

    template:

        metadata:

            labels:

                target: libav

        spec:

            containers:

            - name: libav-fuzzer
              image: ouspg/libfuzzer-libav:latest
